---
title: "Lego Analysis"  
source: "TidyTuesday data sets"
author:
  - name: "William Tang"                   
    StudentID:
    email: ""       
    
  - name: "Rong Chen"                     
    StudentID:
    email: ""
  
  - name: "Prem MV"                     
    StudentID:
    email: ""    
  
  - name: "Zhaouyu Zhang"                     
    StudentID:
    email: "" 
    
    
date: "30 May 2025"                       
format:
  pdf:
     Theme: Journal
---

## Title : Brick by Brick, A Lego Analysis

------------------------------------------------------------------------

### Table of Contents

1.  Title and Authors
2.  Table of contents
3.  Introduction
4.  Executive Summary
5.  Methodology
6.  Results
7.  Discussion, conclusion and recommendations

------------------------------------------------------------------------

## Introduction

Lego, originating from Denmark, was officially founded in the year 1934 by Ole Kirk Christiansen and is one of the world’s most iconic toy companies. Initially Christiansen was a carpenter who was making wooden toys but as time passed by, he adapted to Kiddi-craft(Self blocking Bricks) and then automatic binding bricks were invented. Over the years, Lego has expanded the production line vastly by producing theme based Lego-sets like Star-wars, Harry Potter, Marvel etc... and the very first store to open anywhere in the world was in Sydney, Australia, in the year 1984. Currently, the most biggest Lego set available is the world map set consisting of 11,695 pieces and there are much more sets like these which really keeps you occupied. Even though Lego stopped patent for Lego bricks a long time ago, its competitors could not stand a chance in the toy-construction market for example Lego sued the CoCo Toy Company for copyright infringement and the company has to cease manufacture of the products. The source for the dataset is TidyTuesday and this community has taken the liberty to aggregate that year’s releases into a publicly available dataset with the help of Rebrickable, who maintains and updates the Lego Parts/Sets/Colors of every official LEGO set. Beyond physical bricks, LEGO has expanded into digital games like LEGO Star Wars, LEGO Fortnite and movies, TV series. The methodology includes exploring of the vast data, combinnig data-sets and also includes graphs to understand about themes of Lego set and gives complexity of colours and number of parts of LEGO from the beginning till date.

---

## Executive Summary

Using the 2022 TidyTuesday LEGO dataset of over 1,100 sets, we conducted a descriptive analysis to explore theme prevalence and set complexity over the years. 
After data cleaning, combining and standardization, we produced a theme‐popularity bar chart and a chart with median number of parts over the year to understand trends in Lego themes and complexity in number of parts and colors. 
By looking over the trends in the number of theme sets, we identify the trends in Lego's product strategy and its expansion. 
We came to a conclusion that marketing and sales teams spotlight these high impact themes and test promotions for rising themes to stay where they are in the toy market.

------------------------------------------------------------------------

## Problem Questions - Our motivation for this Analysis

From the analysis made, we as a group decided to further analyise more about 3 main questions,

**1. What were the most popular and least popular themes in LEGO?**

Our motivation - 
We were motivated by LEGO’s long-standing success in adapting its product lines to pop culture and current trends. LEGO has aligned its themes with what is popular at the time for example, when the Marvel movies were released, they entered into manufacturing of Marvel Hero sets or these days F1 is gaining more popularity among the younger generation they entered this entertainment sports field as well where you could build model cars of F1 to keep it as a display piece!. The main reason Lego has so many themes is because it adapts to the most trending thing happening at that time and releases limited edition sets for people to collect.
Our analysis helps us understand which themes have received the most and least attention. From the graph, we can see that Technic is among the most popular themes, yet it has only 64 number of sets suggesting that popularity may also be influenced by part complexity or set reputation rather than just quantity and talking about least popular, Zooters is one of the least popular themes, with only 9 sets ever released.


**2. How has the complexity of LEGO sets changed over the years??**

The main reason we decided to further on this question is because it helps us understand LEGO’s growth in terms of design and difficulty and the solution we arrived for this it to look at how the median number of parts per set has changed over the years. The sets in the early years had fewer pieces and were much simpler. Not that there are simpler sets now but in recent years—especially after 2010 there’s a clear increase in the number of parts per set, showing that LEGO is now making more detailed and complex builds. This increase in complexity tells us that LEGO’s effort to appeal to broader audience, not only for kids but for elders to by offering challenging builds and large sets.


**3. What are the largest LEGO sets available officially??**

Reason behind this question is we wanted to find out the largest sets Lego has to offer for us and wanted to know about color complexity as well. So we merged these two to get a clear result. We combined both part count and color data for the Top 20 largest sets and arrived at a clearer picture. From our analysis, we found that the World Map is the largest set ever released, with over 11,000 pieces and no longer available now. Other massive sets include the NINJAGO City Gardens, Titanic, and Millennium Falcon, each featuring thousands of pieces and a wide variety of colors. Lego just does'nt adapt and release a theme or a set which is just popular and trending, it looks at the legacy it had, tributes to make like monuments - Taj Mahal, Effiel Tower etc and various other reasons. This also shows that as LEGO sets get larger, they also become more visually diverse and detailed for builders and collectors to buy them for themselves.

---