---
title: "Lego Analysis"
format: 
  revealjs:
    theme: sky
    slideNumber: true
    fontSize: 18
    transition: fade
editor: visual
---

### LEGO's evolution: Insights into theme popularity and set complexity

<br><br>

#### Group Members:

1.  William Tang
2.  Prem MV
3.  Rong Chen
4.  Zhaoyu Zhang

------------------------------------------------------------------------

#### Introduction

**Origins & Innovation** - Billund, Denmark (1934) - Ole Kirk Christiansen.

**Our Approach** - 2022 TidyTuesday dataset via Rebrickable

**Global Expansion** - First store open in Sydney (1984)

**Brand Diversification** - Beyond bricks, also entered digital games like LEGO Star Wars, LEGO Fortnite and even movies, TV series.

------------------------------------------------------------------------

#### Data-set Overview

-   **Source:** TidyTuesday 2022 LEGO dataset - Rebrickable API).

-   **Fields:** Theme, release year and piece count.

-   **Scope:** No sales or revenue data—only set metadata.

------------------------------------------------------------------------

#### Analysis Questions

1.  What were the most popular and least popular themes in LEGO?

2.  How has the complexity of LEGO sets changed over the years?

3.  What are the largest LEGO sets available officially?

------------------------------------------------------------------------

#### Methodology

-   Used TidyTuesday LEGO dataset from Rebrickable (theme names, part counts, colour and year)

-   Filtered out sets with missing or zero part counts

-   Initial exploration \@fig-theme_by_parts

------------------------------------------------------------------------

:::: columns
#### Theme popularity

::: {.column width="50%"}
-   Grouped sets by theme and calculated set count and median part count \@fig-most_popular & \@fig-least_popular

-   Top 20 most and least popular themes

-   Bar length = \# of sets, fill = median parts count
:::
::::

------------------------------------------------------------------------

:::: columns
#### Trend over time

::: {.column width="50%"}
-   Analysed median part counts and colour diversity by year \@fig-parts_trend & \@fig-color_diversity

<!-- -->

-   Trend line added for better visibility
:::
::::

------------------------------------------------------------------------

:::: columns
#### Largest Sets Analysis

::: column
-   Top 20 largest sets by part count

-   Bars segmented by actual hex colours to show colour usage per set
:::
::::
